/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/caicloud/crd-sample/pkg/apis/labels/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LabelCounterLister helps list LabelCounters.
type LabelCounterLister interface {
	// List lists all LabelCounters in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.LabelCounter, err error)
	// Get retrieves the LabelCounter from the index for a given name.
	Get(name string) (*v1alpha1.LabelCounter, error)
	LabelCounterListerExpansion
}

// labelCounterLister implements the LabelCounterLister interface.
type labelCounterLister struct {
	indexer cache.Indexer
}

// NewLabelCounterLister returns a new LabelCounterLister.
func NewLabelCounterLister(indexer cache.Indexer) LabelCounterLister {
	return &labelCounterLister{indexer: indexer}
}

// List lists all LabelCounters in the indexer.
func (s *labelCounterLister) List(selector labels.Selector) (ret []*v1alpha1.LabelCounter, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LabelCounter))
	})
	return ret, err
}

// Get retrieves the LabelCounter from the index for a given name.
func (s *labelCounterLister) Get(name string) (*v1alpha1.LabelCounter, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("labelcounter"), name)
	}
	return obj.(*v1alpha1.LabelCounter), nil
}
