/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	labelsv1alpha1 "github.com/caicloud/crd-sample/pkg/apis/labels/v1alpha1"
	clientset "github.com/caicloud/crd-sample/pkg/client/clientset"
	internalinterfaces "github.com/caicloud/crd-sample/pkg/client/informers/internalinterfaces"
	v1alpha1 "github.com/caicloud/crd-sample/pkg/client/listers/labels/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LabelCounterInformer provides access to a shared informer and lister for
// LabelCounters.
type LabelCounterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LabelCounterLister
}

type labelCounterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewLabelCounterInformer constructs a new informer for LabelCounter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLabelCounterInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLabelCounterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredLabelCounterInformer constructs a new informer for LabelCounter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLabelCounterInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LabelsV1alpha1().LabelCounters().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LabelsV1alpha1().LabelCounters().Watch(options)
			},
		},
		&labelsv1alpha1.LabelCounter{},
		resyncPeriod,
		indexers,
	)
}

func (f *labelCounterInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLabelCounterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *labelCounterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&labelsv1alpha1.LabelCounter{}, f.defaultInformer)
}

func (f *labelCounterInformer) Lister() v1alpha1.LabelCounterLister {
	return v1alpha1.NewLabelCounterLister(f.Informer().GetIndexer())
}
