/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/caicloud/crd-sample/pkg/apis/labels/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLabelCounters implements LabelCounterInterface
type FakeLabelCounters struct {
	Fake *FakeLabelsV1alpha1
}

var labelcountersResource = schema.GroupVersionResource{Group: "labels.caicloud.io", Version: "v1alpha1", Resource: "labelcounters"}

var labelcountersKind = schema.GroupVersionKind{Group: "labels.caicloud.io", Version: "v1alpha1", Kind: "LabelCounter"}

// Get takes name of the labelCounter, and returns the corresponding labelCounter object, and an error if there is any.
func (c *FakeLabelCounters) Get(name string, options v1.GetOptions) (result *v1alpha1.LabelCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(labelcountersResource, name), &v1alpha1.LabelCounter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LabelCounter), err
}

// List takes label and field selectors, and returns the list of LabelCounters that match those selectors.
func (c *FakeLabelCounters) List(opts v1.ListOptions) (result *v1alpha1.LabelCounterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(labelcountersResource, labelcountersKind, opts), &v1alpha1.LabelCounterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LabelCounterList{}
	for _, item := range obj.(*v1alpha1.LabelCounterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested labelCounters.
func (c *FakeLabelCounters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(labelcountersResource, opts))
}

// Create takes the representation of a labelCounter and creates it.  Returns the server's representation of the labelCounter, and an error, if there is any.
func (c *FakeLabelCounters) Create(labelCounter *v1alpha1.LabelCounter) (result *v1alpha1.LabelCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(labelcountersResource, labelCounter), &v1alpha1.LabelCounter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LabelCounter), err
}

// Update takes the representation of a labelCounter and updates it. Returns the server's representation of the labelCounter, and an error, if there is any.
func (c *FakeLabelCounters) Update(labelCounter *v1alpha1.LabelCounter) (result *v1alpha1.LabelCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(labelcountersResource, labelCounter), &v1alpha1.LabelCounter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LabelCounter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLabelCounters) UpdateStatus(labelCounter *v1alpha1.LabelCounter) (*v1alpha1.LabelCounter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(labelcountersResource, "status", labelCounter), &v1alpha1.LabelCounter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LabelCounter), err
}

// Delete takes name of the labelCounter and deletes it. Returns an error if one occurs.
func (c *FakeLabelCounters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(labelcountersResource, name), &v1alpha1.LabelCounter{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLabelCounters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(labelcountersResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.LabelCounterList{})
	return err
}

// Patch applies the patch and returns the patched labelCounter.
func (c *FakeLabelCounters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LabelCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(labelcountersResource, name, data, subresources...), &v1alpha1.LabelCounter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LabelCounter), err
}
