/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/caicloud/crd-sample/pkg/apis/labels/v1alpha1"
	scheme "github.com/caicloud/crd-sample/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LabelCountersGetter has a method to return a LabelCounterInterface.
// A group's client should implement this interface.
type LabelCountersGetter interface {
	LabelCounters() LabelCounterInterface
}

// LabelCounterInterface has methods to work with LabelCounter resources.
type LabelCounterInterface interface {
	Create(*v1alpha1.LabelCounter) (*v1alpha1.LabelCounter, error)
	Update(*v1alpha1.LabelCounter) (*v1alpha1.LabelCounter, error)
	UpdateStatus(*v1alpha1.LabelCounter) (*v1alpha1.LabelCounter, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.LabelCounter, error)
	List(opts v1.ListOptions) (*v1alpha1.LabelCounterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LabelCounter, err error)
	LabelCounterExpansion
}

// labelCounters implements LabelCounterInterface
type labelCounters struct {
	client rest.Interface
}

// newLabelCounters returns a LabelCounters
func newLabelCounters(c *LabelsV1alpha1Client) *labelCounters {
	return &labelCounters{
		client: c.RESTClient(),
	}
}

// Get takes name of the labelCounter, and returns the corresponding labelCounter object, and an error if there is any.
func (c *labelCounters) Get(name string, options v1.GetOptions) (result *v1alpha1.LabelCounter, err error) {
	result = &v1alpha1.LabelCounter{}
	err = c.client.Get().
		Resource("labelcounters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LabelCounters that match those selectors.
func (c *labelCounters) List(opts v1.ListOptions) (result *v1alpha1.LabelCounterList, err error) {
	result = &v1alpha1.LabelCounterList{}
	err = c.client.Get().
		Resource("labelcounters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested labelCounters.
func (c *labelCounters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("labelcounters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a labelCounter and creates it.  Returns the server's representation of the labelCounter, and an error, if there is any.
func (c *labelCounters) Create(labelCounter *v1alpha1.LabelCounter) (result *v1alpha1.LabelCounter, err error) {
	result = &v1alpha1.LabelCounter{}
	err = c.client.Post().
		Resource("labelcounters").
		Body(labelCounter).
		Do().
		Into(result)
	return
}

// Update takes the representation of a labelCounter and updates it. Returns the server's representation of the labelCounter, and an error, if there is any.
func (c *labelCounters) Update(labelCounter *v1alpha1.LabelCounter) (result *v1alpha1.LabelCounter, err error) {
	result = &v1alpha1.LabelCounter{}
	err = c.client.Put().
		Resource("labelcounters").
		Name(labelCounter.Name).
		Body(labelCounter).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *labelCounters) UpdateStatus(labelCounter *v1alpha1.LabelCounter) (result *v1alpha1.LabelCounter, err error) {
	result = &v1alpha1.LabelCounter{}
	err = c.client.Put().
		Resource("labelcounters").
		Name(labelCounter.Name).
		SubResource("status").
		Body(labelCounter).
		Do().
		Into(result)
	return
}

// Delete takes name of the labelCounter and deletes it. Returns an error if one occurs.
func (c *labelCounters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("labelcounters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *labelCounters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("labelcounters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched labelCounter.
func (c *labelCounters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LabelCounter, err error) {
	result = &v1alpha1.LabelCounter{}
	err = c.client.Patch(pt).
		Resource("labelcounters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
